name: Deploy Frontend to S3 + CloudFront
description: Deploys Vite frontend to S3 with optimized caching and CloudFront invalidation

inputs:
  aws_region:
    description: AWS region for S3 deployment
    required: true
  cloudfront_distribution_id:
    description: CloudFront distribution ID for cache invalidation
    required: false
  stage:
    description: Deployment stage (production, staging, dev)
    required: false
    default: production

runs:
  using: composite
  steps:
    - name: Deploy frontend assets to S3 with caching strategy
      shell: bash
      run: |
        set -eo pipefail

        STAGE="${{ inputs.stage }}"
        REGION="${{ inputs.aws_region }}"
        S3_BUCKET="remorai-frontend-${STAGE}"
        DIST_DIR="apps/frontend/dist"

        # Verify build exists
        if [ ! -d "$DIST_DIR" ]; then
          echo "❌ ERROR: Frontend dist directory not found at $DIST_DIR"
          echo "   Build frontend first: pnpm build --filter @apps/frontend"
          exit 1
        fi

        echo "📦 Deploying frontend to S3: s3://${S3_BUCKET}"

        # Step 1: Sync versioned assets with 1-year cache
        # Assets with fingerprints (main.abc123.js, style.def456.css) are safe to cache long-term
        echo "📤 [1/3] Uploading versioned assets with 1-year cache..."
        aws s3 sync "$DIST_DIR" "s3://${S3_BUCKET}" \
          --region "$REGION" \
          --delete \
          --cache-control "public, max-age=31536000, immutable" \
          --exclude "*.html" \
          --exclude "*.map" \
          --metadata "deployment-time=$(date -u +%Y-%m-%dT%H:%M:%SZ),stage=${STAGE}"

        if [ $? -eq 0 ]; then
          echo "   ✅ Versioned assets synced"
        else
          echo "   ❌ Failed to sync assets"
          exit 1
        fi

        # Step 2: Upload index.html with no-cache policy
        # index.html must always be fresh for SPA client-side routing
        echo "📄 [2/3] Uploading index.html with no-cache for fresh routing..."
        if [ -f "$DIST_DIR/index.html" ]; then
          aws s3 cp "$DIST_DIR/index.html" "s3://${S3_BUCKET}/index.html" \
            --region "$REGION" \
            --cache-control "public, max-age=0, must-revalidate" \
            --content-type "text/html; charset=utf-8" \
            --metadata "deployment-time=$(date -u +%Y-%m-%dT%H:%M:%SZ),stage=${STAGE}"
          
          if [ $? -eq 0 ]; then
            echo "   ✅ index.html uploaded"
          else
            echo "   ❌ Failed to upload index.html"
            exit 1
          fi
        fi

        # Step 3: Upload any other HTML files with same no-cache policy
        echo "📄 [3/3] Uploading other HTML files..."
        find "$DIST_DIR" -name "*.html" -not -name "index.html" -print0 | \
        while IFS= read -r -d '' html_file; do
          relative_path="${html_file#$DIST_DIR/}"
          aws s3 cp "$html_file" "s3://${S3_BUCKET}/${relative_path}" \
            --region "$REGION" \
            --cache-control "public, max-age=0, must-revalidate" \
            --content-type "text/html; charset=utf-8" \
            --metadata "deployment-time=$(date -u +%Y-%m-%dT%H:%M:%SZ),stage=${STAGE}"
        done || true

        echo "✅ Frontend assets uploaded to S3"

    - name: Invalidate CloudFront cache
      if: inputs.cloudfront_distribution_id != ''
      shell: bash
      run: |
        DIST_ID="${{ inputs.cloudfront_distribution_id }}"

        if [ -z "$DIST_ID" ]; then
          echo "⚠️ CloudFront distribution ID not provided, skipping invalidation"
          exit 0
        fi

        echo "🔄 Invalidating CloudFront cache for distribution: $DIST_ID"

        # Invalidate only HTML paths for efficiency
        # Versioned assets have 1-year TTL, so no need to invalidate them
        aws cloudfront create-invalidation \
          --distribution-id "$DIST_ID" \
          --paths "/index.html" "/*.html" \
          --region us-east-1

        if [ $? -eq 0 ]; then
          echo "✅ CloudFront invalidation requested"
        else
          echo "⚠️ CloudFront invalidation failed, but deployment succeeded"
        fi
